[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C",
    "target-feature=-crt-static",
    "-C",
    "panic=abort",
    "-C",
    "link-arg=-Wl,--gc-sections",
]

[profile.release]
lto = true
codegen-units = 1
